version: '3'
services:
  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
  sales-service:
    build: ./sales-service
    ports:
      - "5002:5002"
  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"
  shipping-service:
    build: ./shipping-service
    ports:
      - "5004:5004"
  auth-service:
    build: ./auth-service
    ports:
      - "5005:5005"
  inventory-service:
    build: ./inventory-service
    ports:
      - "5006:5006"
  service:
    build: ./service
    ports:
      - "5000:5000"
    depends_on:
      - product-service
      - sales-service
      - payment-service
      - shipping-service
      - auth-service
      - inventory-service
      
      
     

